### ISSUE TITLE
[Suggestion] Define a common vocabulary

### ISSUE THREAD

**Issue by ac360** [serverless/guide#4]
To ensure the reading experience remains consistent and high-quality as this project scales, I recommend creating a vocabulary section in the beginning.  One of the requirements for contributing should be sticking to the declared vocabulary.

Example:

- **Serverless:**
- **Serverless Compute, Function-as-a-Service:**
- **Serverless Architecture:**

**Comment by rupakg** [comment]
Closing this. Incorporated in the Glossary section of the guide.
