### ISSUE TITLE
Need Content : Python Dependencies

### ISSUE THREAD

**Issue by ceefour** [serverless/guide#67]
## Description

Add how to add python library dependencies, e.g. psycopg2.

**Page/Section:** Python

Currently this is confusing, https://serverlesscode.com/post/python-on-serverless-intro/ says "Serverless recommends using the created-by-default vendored/ directory and a component-level requirements.txt file" while aws-python3 template has no "vendored" directory, and I don't know what "component" means (a service?)

Also, is `package: include:` in serverless.yml required ?

Also how to handle binary/compiled dependencies like psycopg2.

**Comment by rupakg** [comment]
@ceefour Thanks for the issue. Looks like this is a framework documentation issue and specifically around Python. I was not planning on digging that deep into specific issues in the guide. I can always look into expanding the Serverless Framework section (WIP) to include a section for "best practices". Does that sound reasonable?

/cc @alexdebrie what do you think?

**Comment by alexdebrie** [comment]
@ceefour You're in luck! I wrote a blog post on how to handle Python dependencies with Serverless -- check the link [here](https://serverless.com/blog/serverless-python-packaging/). 

It handles compiled dependencies like psycopg2 and doesn't hassle with the `vendored/` directory. Please let me know if you have questions after reading that.

Good point by @rupakg on the guide. I agree that I'd like to see _some_ place for things like this to exist, whether in the Guide or elsewhere.

**Comment by rupakg** [comment]
@ceefour I will close this issue for now.
